In [2]:
import numpy as np
import time

In [2]:
l = [1,2,3,4,5,6]


In [3]:
l

[1, 2, 3, 4, 5, 6]

In [4]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

### Numpy vs List
1. Numpy arrays are faster(optimized in C)  
2. Numpy stores data in continuos memory blocks
3. Uses less memory(optimized storage)
4. Built-in mathemetical functions
5. supports direct vectorized operations

In [2]:
#1 -> execution performance
size = 1_000_000

py_list = list(range(size))
start = time.time()
sqr_list = [x**2 for x in py_list]
end = time.time()
print(f"list execution time {end - start} seconds")

#nd-array
np_arr = np.array(py_list)
start = time.time()
sqr_arr = np_arr**2 #vectorization
end = time.time()
print(f"nd-array execution time {end - start} seconds")

list execution time 0.25256776809692383 seconds
nd-array execution time 0.002368927001953125 seconds


In [5]:
#memory
#python list add extra meta data(addtional information about data) that how it's occupy more space
import sys
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
'''
numpy ->
1.homogeneous data types and continuos memory
2.vector operations & c implementions
3.reduce overhead
'''
print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 8000056000000 bytes
numpy array size = 8000000 bytes


### Create array from list

In [6]:
#create array from list
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr), arr2.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21


In [7]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr), arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)


In [8]:
#2d-array
arr_2d = np.array([[1,2,3,4],[4,5,6,7],[7,6,4,3],[5,6,3,2]])
print(arr_2d, arr_2d.shape)

[[1 2 3 4]
 [4 5 6 7]
 [7 6 4 3]
 [5 6 3 2]] (4, 4)


In [10]:
#built-in function to create numpy array
arr1 = np.zeros((2,3), dtype="int64") #prefil
print(arr1, arr1.shape)

arr2 = np.ones((5,)) #prefil
print(arr2, arr2.shape)

arr3 = np.full((3,4), 100)
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1,10)
print(arr5)

arr6 = np.linspace(1, 100, 6) # evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 2 3 4 5 6 7 8 9]
[  1.   20.8  40.6  60.4  80.2 100. ] (6,)


### Properties of numpy

In [12]:
arr = np.array([[1,2,3], [4,5,6], [4,5,3]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [4. 5. 3.]] float64


### Reshaping
* reshaping
* indexing (1d & 2d array)
* fancy & boolean indexing
* slicing

In [14]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flatten = arr.flatten() #2d->1d
print(flatten, flatten.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


### Indexing

In [17]:
#1d
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[3])

#2d
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d[1,2])

1
4
6


In [19]:
#fancey indexing
arr = np.array([1,2,3,4,5])
idx = [0, 1, 4]
print(arr[idx])

[1 2 5]


In [20]:
#Boolean indexing
arr = np.array([1,2,3,4,5,6])

print(arr[arr>2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5 6]
[2 4 6]
[1 3 5]


In [21]:
#Slicing
arr = np.array([1,2,3,4,5,6,7,8])
#[start, end, step]
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5 6 7 8]
[1 2 3 4]
[1 3 5 7]


## Slicing
* python list create a new copy
* python numpy create a view

In [22]:
#copy vs view

nums = [1,2,3,4,5,6]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 20
print(sub_list)
print(nums)



[2, 3]
[20, 3]
[1, 2, 3, 4, 5, 6]


In [24]:
arr = np.array([1,2,3,4,5,6])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 20
print(sub_arr)
print(arr)

[2 3]
[20  3]
[ 1 20  3  4  5  6]


### Data types
* integers: int32, int64
* floating point nums: float32, float64
* boolean: bool
* complex nums: complex64, complex128
* string S(byte-str) & U(unicode-str)
* Object: generic python objects - object

In [25]:
arr = np.array([1,2,3,4,5,6,7])
print(arr, arr.dtype)

[1 2 3 4 5 6 7] int64


In [26]:
arr = np.array([1,2,3,4,5.0,6,7])
print(arr, arr.dtype)

[1. 2. 3. 4. 5. 6. 7.] float64


In [27]:
arr = np.array([1,2,3,4,5,6,7,"prime"])
print(arr, arr.dtype)

['1' '2' '3' '4' '5' '6' '7' 'prime'] <U21


In [29]:
#complex nums
arr = np.array([3 + 7j])
print(arr, arr.dtype)

[3.+7.j] complex128


In [30]:
#object datatypes
arr = np.array(["prime", {1,2,3,4}, 3.24])
print(arr, arr.dtype)

['prime' {1, 2, 3, 4} 3.24] object


### Axes in multi-dimentional array

* 1d -> 1 axis (axis 0)
* 2d -> 2 axes (axis 0 - rows - vertically, axis 1 - columns - horizontally)
* 3d -> 3 axes (axis 0 depth/layers, axis 1 - row in each layers, axis 2 - columns)

In [31]:
# Multi-dimensional arrays
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
# Multi-dimensional arrays
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)

print(np.sum(arr2d))

sum_of_columns = np.sum(arr2d, axis= 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2d, axis= 1)
print(sum_of_rows)

print(arr2d[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [41]:
#3d array
arr3d = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,19], [11,12]]])  #2, 3, 2

print(arr3d, arr3d.shape)

#indexing
print(arr3d[1,1,1])

#slicing
print(arr3d[:, 0, :]) #first row from both layers
arr3d[:, 0, :] = 100
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 19]
  [11 12]]] (2, 3, 2)
19
[[1 2]
 [7 8]]
[[[100 100]
  [  3   4]
  [  5   6]]

 [[100 100]
  [  9  19]
  [ 11  12]]]


### Vectorization

In [3]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr + arr2)

[ 7  9 11 13 15]


In [4]:
#Broadcasting
print(arr + 5)

[ 6  7  8  9 10]


In [2]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])

print(arr.shape)
print(arr2.shape)

print(arr + arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


### Vector normalization

In [4]:
arr = np.array([[1,2], [3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr - mean) / std_dev
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


### Mathmatical funciton

In [3]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))


print(np.mean(arr))
print(np.std(arr))
print(np.sqrt(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
[1.         1.41421356 1.73205081 2.         2.23606798]
3.0
2.0


In [5]:
#power function
print(np.square(arr))
print(np.power(arr,3))
print(np.log(arr))
print(np.exp(arr))

[ 1  4  9 16 25]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [8]:
print(np.round(5.9))
print(np.ceil(4.5))
print(np.floor(6.9))
print(np.trunc(3.14))

6.0
5.0
6.0
3.0


In [9]:
print(np.unique(arr))

[1 2 3 4 5]
